const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description:
      "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 15000,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description:
      "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 12000,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description:
      "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 10000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description:
      "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 25000,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description:
      "Live among the canopy in this unique treehouse retreat. A true nature lover's paradise.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 8000,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Paradise",
    description:
      "Step out of your door onto the white sand. This beachfront property offers incredible sunrise views and luxury amenities.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 20000,
    location: "Cancun",
    country: "Mexico",
  },
  {
    title: "Rustic Cabin in the Woods",
    description:
      "A perfect winter getaway. Enjoy the hot tub while it snows outside in this beautiful and warm timber cabin.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 6500,
    location: "Jackson Hole",
    country: "United States",
  },
  {
    title: "Luxury Modern Mansion",
    description:
      "Live like a celebrity in this stunning ultra-modern mansion featuring an infinity pool and incredible city views.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 55000,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Charming European Apartment",
    description:
      "Right in the historic center. Walk to all the major sights from this incredibly bright and airy apartment.",
    image: "https://images.unsplash.com/photo-1449844908441-8829872d2607?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 9000,
    location: "Paris",
    country: "France",
  },
  {
    title: "Tropical Pool Villa",
    description:
      "Total privacy in this tropical villa. Comes with a private chef, pool access from the living room, and lush gardens.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    price: 32000,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Modern Flat in London",
    description: "Experience the best stay in London. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1de2d9d0cb?auto=format&fit=crop&q=80&w=800",
    price: 21755,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Luxury Villa in Tokyo",
    description: "Experience the best stay in Tokyo. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1de2d9d0cb?auto=format&fit=crop&q=80&w=800",
    price: 9796,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Cozy Apartment in Sydney",
    description: "Experience the best stay in Sydney. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 13614,
    location: "Sydney",
    country: "Australia",
  },
  {
    title: "Spacious House in Rome",
    description: "Experience the best stay in Rome. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 5647,
    location: "Rome",
    country: "Italy",
  },
  {
    title: "Studio Flat in Cape Town",
    description: "Experience the best stay in Cape Town. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 8882,
    location: "Cape Town",
    country: "South Africa",
  },
  {
    title: "Modern Flat in Dubai",
    description: "Experience the best stay in Dubai. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 6847,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Luxury Villa in Singapore",
    description: "Experience the best stay in Singapore. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1de2d9d0cb?auto=format&fit=crop&q=80&w=800",
    price: 6274,
    location: "Singapore",
    country: "Singapore",
  },
  {
    title: "Cozy Apartment in Vancouver",
    description: "Experience the best stay in Vancouver. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 22775,
    location: "Vancouver",
    country: "Canada",
  },
  {
    title: "Spacious House in Amsterdam",
    description: "Experience the best stay in Amsterdam. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 17735,
    location: "Amsterdam",
    country: "Netherlands",
  },
  {
    title: "Studio Flat in Barcelona",
    description: "Experience the best stay in Barcelona. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 18642,
    location: "Barcelona",
    country: "Spain",
  },
  {
    title: "Modern Flat in Lisbon",
    description: "Experience the best stay in Lisbon. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 8896,
    location: "Lisbon",
    country: "Portugal",
  },
  {
    title: "Luxury Villa in Prague",
    description: "Experience the best stay in Prague. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1de2d9d0cb?auto=format&fit=crop&q=80&w=800",
    price: 14809,
    location: "Prague",
    country: "Czech Republic",
  },
  {
    title: "Cozy Apartment in Vienna",
    description: "Experience the best stay in Vienna. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 22066,
    location: "Vienna",
    country: "Austria",
  },
  {
    title: "Spacious House in Berlin",
    description: "Experience the best stay in Berlin. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1de2d9d0cb?auto=format&fit=crop&q=80&w=800",
    price: 7485,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Studio Flat in Kyoto",
    description: "Experience the best stay in Kyoto. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 21840,
    location: "Kyoto",
    country: "Japan",
  },
  {
    title: "Modern Flat in Mumbai",
    description: "Experience the best stay in Mumbai. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 19064,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa in Rio de Janeiro",
    description: "Experience the best stay in Rio de Janeiro. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 20099,
    location: "Rio de Janeiro",
    country: "Brazil",
  },
  {
    title: "Cozy Apartment in Seoul",
    description: "Experience the best stay in Seoul. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 10087,
    location: "Seoul",
    country: "South Korea",
  },
  {
    title: "Spacious House in Istanbul",
    description: "Experience the best stay in Istanbul. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 18642,
    location: "Istanbul",
    country: "Turkey",
  },
  {
    title: "Studio Flat in Bangkok",
    description: "Experience the best stay in Bangkok. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 3885,
    location: "Bangkok",
    country: "Thailand",
  },
  {
    title: "Modern Flat in London",
    description: "Experience the best stay in London. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 3455,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Luxury Villa in Tokyo",
    description: "Experience the best stay in Tokyo. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 11664,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Cozy Apartment in Sydney",
    description: "Experience the best stay in Sydney. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 4638,
    location: "Sydney",
    country: "Australia",
  },
  {
    title: "Spacious House in Rome",
    description: "Experience the best stay in Rome. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 16703,
    location: "Rome",
    country: "Italy",
  },
  {
    title: "Studio Flat in Cape Town",
    description: "Experience the best stay in Cape Town. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 9911,
    location: "Cape Town",
    country: "South Africa",
  },
  {
    title: "Modern Flat in Dubai",
    description: "Experience the best stay in Dubai. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 9808,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Luxury Villa in Singapore",
    description: "Experience the best stay in Singapore. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 5627,
    location: "Singapore",
    country: "Singapore",
  },
  {
    title: "Cozy Apartment in Vancouver",
    description: "Experience the best stay in Vancouver. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 10086,
    location: "Vancouver",
    country: "Canada",
  },
  {
    title: "Spacious House in Amsterdam",
    description: "Experience the best stay in Amsterdam. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 3538,
    location: "Amsterdam",
    country: "Netherlands",
  },
  {
    title: "Studio Flat in Barcelona",
    description: "Experience the best stay in Barcelona. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1de2d9d0cb?auto=format&fit=crop&q=80&w=800",
    price: 11880,
    location: "Barcelona",
    country: "Spain",
  },
  {
    title: "Modern Flat in Lisbon",
    description: "Experience the best stay in Lisbon. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 11604,
    location: "Lisbon",
    country: "Portugal",
  },
  {
    title: "Luxury Villa in Prague",
    description: "Experience the best stay in Prague. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1de2d9d0cb?auto=format&fit=crop&q=80&w=800",
    price: 4292,
    location: "Prague",
    country: "Czech Republic",
  },
  {
    title: "Cozy Apartment in Vienna",
    description: "Experience the best stay in Vienna. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 4058,
    location: "Vienna",
    country: "Austria",
  },
  {
    title: "Spacious House in Berlin",
    description: "Experience the best stay in Berlin. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 10259,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Studio Flat in Kyoto",
    description: "Experience the best stay in Kyoto. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 5321,
    location: "Kyoto",
    country: "Japan",
  },
  {
    title: "Modern Flat in Mumbai",
    description: "Experience the best stay in Mumbai. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 22458,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Luxury Villa in Rio de Janeiro",
    description: "Experience the best stay in Rio de Janeiro. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 15612,
    location: "Rio de Janeiro",
    country: "Brazil",
  },
  {
    title: "Cozy Apartment in Seoul",
    description: "Experience the best stay in Seoul. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
    price: 15995,
    location: "Seoul",
    country: "South Korea",
  },
  {
    title: "Spacious House in Istanbul",
    description: "Experience the best stay in Istanbul. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 11961,
    location: "Istanbul",
    country: "Turkey",
  },
  {
    title: "Studio Flat in Bangkok",
    description: "Experience the best stay in Bangkok. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 9096,
    location: "Bangkok",
    country: "Thailand",
  },
  {
    title: "Modern Flat in London",
    description: "Experience the best stay in London. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 3943,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Luxury Villa in Tokyo",
    description: "Experience the best stay in Tokyo. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 21446,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Cozy Apartment in Sydney",
    description: "Experience the best stay in Sydney. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 10528,
    location: "Sydney",
    country: "Australia",
  },
  {
    title: "Spacious House in Rome",
    description: "Experience the best stay in Rome. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    price: 5032,
    location: "Rome",
    country: "Italy",
  },
  {
    title: "Studio Flat in Cape Town",
    description: "Experience the best stay in Cape Town. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1de2d9d0cb?auto=format&fit=crop&q=80&w=800",
    price: 19813,
    location: "Cape Town",
    country: "South Africa",
  },
  {
    title: "Modern Flat in Dubai",
    description: "Experience the best stay in Dubai. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    price: 11420,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Luxury Villa in Singapore",
    description: "Experience the best stay in Singapore. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 7806,
    location: "Singapore",
    country: "Singapore",
  },
  {
    title: "Cozy Apartment in Vancouver",
    description: "Experience the best stay in Vancouver. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 8183,
    location: "Vancouver",
    country: "Canada",
  },
  {
    title: "Spacious House in Amsterdam",
    description: "Experience the best stay in Amsterdam. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 16594,
    location: "Amsterdam",
    country: "Netherlands",
  },
  {
    title: "Studio Flat in Barcelona",
    description: "Experience the best stay in Barcelona. This beautiful property has all the amenities you need for a comfortable stay.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    price: 22111,
    location: "Barcelona",
    country: "Spain",
  },
];

module.exports = { data: sampleListings };
